apiVersion: v1
kind: Service
metadata: 
  name: nodedemo-server-service
  labels:
    app: nodedemo-server
spec:
  selector:
    app: nodedemo-server
  ports:
  - port: 8000
    protocol: TCP
    nodePort: 30061
  type: LoadBalancer